


export const metadata = {
  title: "Zulip Za Sirotinju",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
    </html>
  );
}